### ISSUE TITLE
examples/html_out doesn't render diagram svgs

### ISSUE THREAD

**Issue by gobengo** [staruml/metadata-json#1]
Cool lib!

I did the following
- clone
- npm install
- ed examples
- `node ex_html.js`

It completes without output, and puts lots of good HTML in ./html-out.

However, it creates a ',.diagrams' directory that is empty. This makes it so when I am browsing the HTML, the images (to .svg URLs) all 404 and don't load.

Is SVG rendering supported currently in that example? Or is there a better way than https://github.com/staruml/metadata-json/blob/master/examples/ex_html.js#L7

**Comment by niklauslee** [comment]
Diagram export is not supported yet.

**Comment by niklauslee** [comment]
Now this feature is supported. Please refer to README.md
