### ISSUE TITLE
Open Source or Closed?

### ISSUE THREAD

**Issue by chrisritterc9** [staruml/metadata-json#3]
Hi Minkyu,

Metadata-JSON seems pretty capable but the license header in some files says:
- NOTICE:  All information contained herein is, and remains the
- property of Minkyu Lee. The intellectual and technical concepts
- contained herein are proprietary to Minkyu Lee and may be covered
- by Republic of Korea and Foreign Patents, patents in process,
- and are protected by trade secret or copyright law.
- Dissemination of this information or reproduction of this material
- is strictly forbidden unless prior written permission is obtained
- from Minkyu Lee (niklaus.lee@gmail.com).

Other files say MIT License - Is the library MIT or proprietary?

Thanks for the clarification.

**Comment by niklauslee** [comment]
That is my mistake. The header comments are remained by copying from my private source repository. I will change the header comments as soon as possible. All source codes are under MIT License.
